query ($route: String) {
      fetchedCompetition: competitions(where: {routeName: {_eq: $route}}) {
            id
            name
            routeName
            description
            dateRange
            type
            updatedAt
            user
            cup {
                id
                isDoubleElimination
                size
            }
            group {
                id
                size
                isDouble
                winnerPoints
                loserPoints
                drawPoints
                isDrawEnable
            }
      }
}